name: Run Ubuntu VM

on:
  workflow_dispatch:

jobs:
  run-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Install QEMU
        run: |
          sudo apt update
          sudo apt install -y qemu-system-x86 qemu-utils

      - name: Download Ubuntu Cloud Image
        run: |
          curl -LO https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img

      - name: Run Ubuntu VM in background
        run: |
          qemu-system-x86_64 \
            -nographic \
            -m 2048 \
            -smp 2 \
            -hda focal-server-cloudimg-amd64.img \
            -net nic -net user,hostfwd=tcp::2222-:22 \
            -enable-kvm &
