name: Persistent KVM VM with tmate

on:
  workflow_dispatch:

jobs:
  start-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y qemu-kvm cloud-image-utils genisoimage \
                              openssh-client wget tmate net-tools

      - name: Download Ubuntu cloud image
        run: |
          wget -q https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img \
            -O ubuntu.img

      - name: Create cloud-init config (auto-login root, SSH key, persistence)
        run: |
          mkdir -p seed
          cat > seed/meta-data <<EOF
          instance-id: github-vm
          local-hostname: githubvm
          EOF

          cat > seed/user-data <<EOF
          #cloud-config
          users:
            - name: root
              ssh-authorized-keys:
                - $(curl -s https://api.github.com/repos/${{ github.repository_owner }}/keys | grep '"key":' | head -n1 | cut -d'"' -f4)
              sudo: ALL=(ALL) NOPASSWD:ALL
              shell: /bin/bash
          ssh_pwauth: false
          disable_root: false
          EOF

          cloud-localds seed.img seed/user-data seed/meta-data

      - name: Create persistent disk
        run: |
          qemu-img create -f qcow2 persistent.img 10G
          qemu-img resize ubuntu.img +0G  # Optional - just to show no change

      - name: Launch VM in background with KVM and SSH forwarding
        run: |
          nohup qemu-system-x86_64 \
            -enable-kvm \
            -m 2048 -smp 2 \
            -drive file=persistent.img,format=qcow2 \
            -drive file=ubuntu.img,format=qcow2 \
            -drive file=seed.img,format=raw \
            -net nic \
            -net user,hostfwd=tcp::2222-:22 \
            -nographic > vm.log 2>&1 &

      - name: Wait for SSH to respond (up to 60s)
        run: |
          for i in {1..30}; do
            nc -z localhost 2222 && echo "VM is up!" && break
            echo "Waiting for VM..."
            sleep 2
          done

      - name: Start tmate session (SSH to VM from here)
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false
