name: Persistent Fast QEMU VM (Lightwget Style)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'  # Restart every 5 hours

jobs:
  vm-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y qemu-system-x86 qemu-utils cloud-image-utils genisoimage wget tmate gh

    - name: Restore persistent disk or create new
      run: |
        echo "Downloading persistent disk if exists..."
        if gh release view vm-disk &>/dev/null; then
          gh release download vm-disk -p persistent.img
          echo "Disk restored!"
        else
          echo "Creating persistent disk for first time..."
          wget -q https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img -O base.img
          qemu-img create -f qcow2 -b base.img -F qcow2 persistent.img 10G
        fi

    - name: Create cloud-init (first-time root setup)
      run: |
        mkdir -p seed
        echo "instance-id: githubvm" > seed/meta-data
        cat > seed/user-data <<EOF
        #cloud-config
        users:
          - name: root
            ssh-authorized-keys:
              - $(curl -s https://api.github.com/users/${{ github.actor }}/keys | grep '"key":' | head -n1 | cut -d'"' -f4)
            sudo: ALL=(ALL) NOPASSWD:ALL
            shell: /bin/bash
        ssh_pwauth: false
        disable_root: false
        EOF
        cloud-localds seed.img seed/user-data seed/meta-data

    - name: Boot VM with persistent disk only
      run: |
        nohup qemu-system-x86_64 \
          -enable-kvm \
          -m 16000 -smp 4 \
          -drive file=persistent.img,format=qcow2,if=virtio \
          -drive file=seed.img,format=raw \
          -net nic -net user,hostfwd=tcp::2222-:22 \
          -nographic > vm.log 2>&1 &
        echo $! > vm.pid

    - name: Wait for VM SSH
      run: |
        for i in {1..30}; do
          nc -z localhost 2222 && echo "VM ready!" && break
          echo "Waiting..."
          sleep 2
        done

    - name: Start tmate session
      uses: mxschmitt/action-tmate@v3

    - name: Shutdown VM
      run: |
        if [ -f vm.pid ]; then
          kill $(cat vm.pid)
        fi
        sleep 5

    - name: Upload updated disk to GitHub
      if: always()
      run: |
        echo "Replacing old release..."
        gh release delete vm-disk --yes || true
        gh release create vm-disk persistent.img -t "VM Disk" -n "Auto backup"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
